import "swiper/css";
import "./globals.css";
import "swiper/css/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" className="rtl" dir="rtl">
      <body>{children}</body>
    </html>
  );
}
